### ISSUE TITLE
[REQ] Update list or found count before search is complete

### ISSUE THREAD

**Issue by gingerbeardman** [sveinbjornt/KatSearch#1]
It seems to me that all matches are shown only after search is complete.

It would be better if they were shown one-by-one as they are found.

Compare these videos (both apps take the same amount of time to return all matches, 2m22s)

Find Any File
https://youtu.be/XKzEk4MYDWg

KatSearch
https://youtu.be/PMrbkoj1HY8

**Comment by sveinbjornt** [comment]
Search results are now live.
