### ISSUE TITLE
Possible use for KatSearch

### ISSUE THREAD

**Issue by concept10** [sveinbjornt/KatSearch#2]
I've just pondered the best use of this app for my use case:

- Start by tagging files and folders for relevant work
- Search macOS APFS/HFS/mounted drives for all files and create array object with contents

- Use this collected metadata to move the tagged files/folder to predefined fs paths for organization. 

Maybe I could string these actions together using Shortcuts but rather use swift or other newer lang. 

Any tips/suggestions?

**Comment by gingerbeardman** [comment]
Why does that workflow require KatSearch specifically?

Seems possible using `mdfind`, Hazel, Folder Actions, Automator, etc.

**Comment by concept10** [comment]
@gingerbeardman It doesn't specifically require KatSearch, of course. Looking for insight on using tools from your suite. The best I've found.  I personally keep large repository of open source projects for use in industry running about 50 storage pools and trying to find best way to organize it all.

**Comment by concept10** [comment]
You may close this issue as it probably would have been better as discussion.
